### ISSUE TITLE
Using --incliude-targets option fails on coveralls step

### ISSUE THREAD

**Issue by michael-simonetta** [trax-retail/xccov2lcov#2]
Command I am running:

`swift run xccov2lcov cov.json > lcov.info --include-targets [Broadcast,BroadcastLiveStream,ChatKit]`

Error code on uploading to Coveralls:
Error:  "2022-06-30T01:30:58.016Z"  'error from lcovParse: ' 'Failed to parse string'
Error:  "[2](https://github.com/loopsocial/ando/runs/7123298474?check_suite_focus=true#step:8:3)022-06-30T01:30:58.017Z"  'input: ' '\n'
Error:  "2022-06-[3](https://github.com/loopsocial/ando/runs/7123298474?check_suite_focus=true#step:8:4)0T01:30:58.017Z"  'error from convertLcovToCoveralls'
Error: Failed to parse string

Note: Without the include-targets option the upload works as expected.

**Comment by humblehacker** [comment]
Hi @msimonetta1,

You're close! The correct command would be:

```bash
swift run xccov2lcov cov.json \
  --include-targets Broadcast \
  --include-targets BroadcastLiveStream \
  --include-targets ChatKit  > lcov.info
```

I think the naming of the option led to your confusion, so I've just released a version 1.0.0 that changes the name to `--include-target` to reflect that it must only refer to a single target, and I've updated the README to describe this. So if you update to 1.0.0 your command will be:

```bash
swift run xccov2lcov cov.json \
  --include-target Broadcast \
  --include-target BroadcastLiveStream \
  --include-target ChatKit  > lcov.info
```

Hope this helps!
